Free_Gold_Watch/config/routes.rb
FreeGoldWatch::Application.routes.draw do
  devise_for :users

  root 'games#index'

  resources :games do 
    resources :scores, only: :create
  end

  

end

Free_Gold_Watch/app/models/game.rb
class Game < ActiveRecord::Base


	validates :name, presence: true
	#validates :year_released, length: is: 4
	#validates :image, format: /\A\w+\.png\z/

	belongs_to :user
 	has_many :scores
 	has_many :scorers, through: :scores, source: :user
 

	def self.search_for(query)
		where('name LIKE :query or year_released LIKE :query', query: "%#{query}%")
	
	end


end

Free_Gold_Watch/app/models/score.rb
class Score < ActiveRecord::Base

	belongs_to :user
	belongs_to :game

	
end

Free_Gold_Watch/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :games
  has_many :scores

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

Free_Gold_Watch/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

Free_Gold_Watch/app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :load_game, only: [:edit, :show, :update]

	def index
		@games = Game.search_for(params[:q])
	end

	def new
		@game = Game.new
	end

	def show
		@game = Game.find(params[:id])
		@score = Score.new
    	#@scores = Score.search_for(params[:q])
	end

	def create
		@game = Game.new(game_params)
		@game.active = true
		#@game.pintype = true

		if @game.save
			redirect_to @game
    	else
      		render 'new'
	    end
	end

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@game = Game.find(params[:id])
		@game.update game_params
		redirect_to @game
	end

private
    def game_params
      params.require('game').permit(:name, :year_released, :pintype)
    end

		def load_game
			@game = Game.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			flash[:notice] = "Invalid game ID #{params[:id]}"
			redirect_to root_path
		end	

end

Free_Gold_Watch/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
	def create
    	if user_signed_in?
	        safe_score = params.require(:score).permit(:value).merge(game_id: params[:game_id])
	        @score = current_user.scores.create safe_score
	        redirect_to @score.game
	    end
	end

end

Free_Gold_Watch/app/helpers/application_helper.rb
module ApplicationHelper
end

Free_Gold_Watch/app/helpers/games_helper.rb
module GamesHelper
end

Free_Gold_Watch/app/helpers/players_helper.rb
module PlayersHelper
end

Free_Gold_Watch/app/helpers/scores_helper.rb
module ScoresHelper
end

Free_Gold_Watch/app/views/games/_form.html.erb
<% if @game.errors.any? %>
	<h2> There was an error in saving your game</h2>
	<ul>
		<% @game.errors.full_messages.each do |m| %>
			<li><%= m %></li>
		<% end %>
	</ul>
<% end %>


<%= form_for @game do |f| %>
	<fieldset>
		<div class='fields'> 
			<%= f.label :name, "Name" %>
			<%= f.text_field :name%>
		</div>	
	
	    <div class="field">
	      <%= f.label :year_released, "Year Released?" %><br>
	      <%= f.text_field :year_released %>
	    </div>
	
		<div class="field">
			<%= f.label :pintype, "Pinball" %>
			<%= f.radio_button :pintype, true, :checked => true%>
			<%= f.label :pintype, "Arcade" %>
      		<%= f.radio_button :pintype, false, :checked => false%>
  		</div>
	
		<div class="field">
			<%= f.label :active, "In the shop" %> 
			<%= f.radio_button :active, true, :checked => true%> 
			<%= f.label :active, "Removed from shop" %>
      		<%= f.radio_button :active, false, :checked => false%>
  		</div>
	
		
	</fieldset>
	<%= f.submit %>
<% end %>

Free_Gold_Watch/app/views/games/_list.html.erb
<ul>
	<% @games.each do |n|%>
		<li><%= link_to n.name, game_path(n) %></li>
	<%end%>
</ul>

<%# @shirts.each do |shirt|%>
	<div>
		<h3><%#= link_to shirt.name, shirt_path(shirt.id)%></h3>
		<p><%#= shirt.description %></p>
		<p><%#= image_tag "shirts/" + shirt.image%></p>
	</div>
<%# end %>

Free_Gold_Watch/app/views/games/edit.html.erb
<h1>Edit Game</h1>
<%= render 'form' %>
<br>
<%= link_to 'Back to games', root_path %>

Free_Gold_Watch/app/views/games/index.html.erb
<h1>Welcome to the Free Gold Watch scoreboard</h1>
<br/>

<p><%= flash[:notice] %></p>

<br>


<%= form_tag "/", method: "GET" do %>
	<%= text_field_tag :q %>
	<%= submit_tag  "Search"%>
<% end %>

<br/><br>

<%= render "list"%>


<% if user_signed_in? %>	
	<h3><%= link_to "new game", new_game_path %></h3>
<% end %>

<!-- 
<p>this page should show a list of current games</p>
<p>anyone can select a game to see its pics/scores</p>
<p>users can add scores, and add/archive games</p> -->

Free_Gold_Watch/app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form'%>
<br>
<%= link_to 'Back to games', root_path %>

Free_Gold_Watch/app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<h2><%= @game.year_released %></h2>
<%#= image_tag "games/" + @game.image%>
<br>

<!-- <ul>
	<%# @scores.each do |n|%>
		<li><%#= n.value, n.created_at %></li>
	<%#end%>
</ul>
 -->

<%= form_for [@game, @score] do |f| %>
<%= f.label :value, "New Score" %>
<%= f.text_area :value, :cols => 20 %>
<%= f.submit %>
<% end %>


<h2>Your Scores </h2>
<ul>
<% @game.scores.each do |score| %>
<li><%= "#{score.created_at.to_date}-------#{score.value}"   %></li>
<% end %>
</ul>



<% if @game.pintype? %>
	<p><%= "This is a pinball machine"%></p>
<% else %>
	<p><%= "This is an arcade game"%></p>
<% end %>

<% if @game.active? %>
	<p><%= "This is in the shop right now!"%></p>
<% else %>
	<p><%= "This is currently out of circulation"%></p>
<% end %>


<% if user_signed_in? %>	
	<%= link_to "Edit", edit_game_path(@game)%>
<% end %>


<br>
<%= link_to 'Back to games', root_path %>

Free_Gold_Watch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Free Gold Watch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
	<p>Logged in as <%= current_user.email%> </p>
	<%=link_to "Logout", destroy_user_session_path,method: :delete%>
<% else %>
	<p><%= link_to "Sign Up", new_user_registration_path%> | <%= link_to "Login", new_user_session_path%></p>
<% end %>

<!-- <div class="container" id="nav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Test button</a>
    </div>
    <div class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <input type="text" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" placeholder="Password" class="form-control">
        </div>
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>
    </div><!--/.navbar-collapse -->
<!-- </div>

<div class="container"> -->	
<!--  -->
	<%= yield %>
<!-- </div> -->


</body>

</html>